const FETCH_HOTELS = 'FETCH_HOTELS';
const FETCH_HOTELS_LOADING = 'FETCH_HOTELS_LOADING';
const DELETE_HOTEL = 'DELETE_HOTEL';
const NOTIFICATION = 'NOTIFICATION';

export { FETCH_HOTELS, NOTIFICATION, FETCH_HOTELS_LOADING, DELETE_HOTEL };
